#!/usr/bin/env bash

set -euo pipefail

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
waybar_dir="$config_home/waybar"
panel_colors="$waybar_dir/panel-colors.css"
ghostty_dir="$config_home/ghostty"
kitty_dir="$config_home/kitty"
rofi_dir="$config_home/rofi"
swaync_dir="$config_home/swaync"

color_from_panel() {
    local name="$1" fallback="$2"
    sed -n "s/^@define-color ${name} \([^;]*\);.*/\1/p" "$panel_colors" 2>/dev/null | tail -n 1 | grep -E '^#[0-9A-Fa-f]{6}$' || printf '%s\n' "$fallback"
}

accent="$(color_from_panel accent '#e23864')"
text="$(color_from_panel text '#f3edf2')"
muted="$(color_from_panel muted '#b8aeb8')"
background="#171217"
background_alt="#2a1c23"

write_atomic() {
    local destination="$1"
    local temporary
    mkdir -p "$(dirname "$destination")"
    temporary="$(mktemp "${destination}.XXXXXX")"
    cat >"$temporary"
    chmod --reference="$destination" "$temporary" 2>/dev/null || true
    mv "$temporary" "$destination"
}

write_atomic "$ghostty_dir/wallust.conf" <<EOF
# Generated by DeblestiaSystemThemeSync.sh.
background = $background
foreground = $text
cursor-color = $accent
selection-background = $background_alt
selection-foreground = $text
palette = 0=$background
palette = 1=$accent
palette = 2=#a8d8ad
palette = 3=#f1c27d
palette = 4=#7aa2f7
palette = 5=#c8a7ff
palette = 6=#79c8c5
palette = 7=$text
palette = 8=$muted
palette = 9=#ff7f9f
palette = 10=#b8e6b8
palette = 11=#ffe0a3
palette = 12=#9fc1ff
palette = 13=#e0b8ff
palette = 14=#a5e8e5
palette = 15=#ffffff
EOF

kitty_theme="$kitty_dir/kitty-themes/99-Deblestia-Wallpaper.conf"
write_atomic "$kitty_theme" <<EOF
# Generated by DeblestiaSystemThemeSync.sh.
foreground $text
background $background
cursor $accent
selection_foreground $text
selection_background $background_alt
url_color $accent
active_tab_foreground $text
active_tab_background $accent
inactive_tab_foreground $muted
inactive_tab_background $background_alt
color0 $background
color1 $accent
color2 #a8d8ad
color3 #f1c27d
color4 #7aa2f7
color5 #c8a7ff
color6 #79c8c5
color7 $text
color8 $muted
color9 #ff7f9f
color10 #b8e6b8
color11 #ffe0a3
color12 #9fc1ff
color13 #e0b8ff
color14 #a5e8e5
color15 #ffffff
EOF
if [ -f "$kitty_dir/kitty.conf" ] && ! grep -Fqx 'include ./kitty-themes/99-Deblestia-Wallpaper.conf' "$kitty_dir/kitty.conf"; then
    printf '\ninclude ./kitty-themes/99-Deblestia-Wallpaper.conf\n' >>"$kitty_dir/kitty.conf"
fi

write_atomic "$rofi_dir/DebianGlass.rasi" <<EOF
/* Generated by DeblestiaSystemThemeSync.sh. */
* {
  bg: rgba(23, 18, 23, 96%);
  bg-alt: rgba(42, 28, 35, 98%);
  fg: $text;
  muted: $muted;
  accent: $accent;
  background-color: transparent;
  text-color: @fg;
}
window { border: 2px; border-color: @accent; border-radius: 14px; background-color: @bg; padding: 14px; }
mainbox { spacing: 12px; }
inputbar { padding: 12px; border-radius: 10px; background-color: @bg-alt; children: [prompt, entry]; }
prompt { text-color: @accent; padding: 0 10px 0 0; }
entry { placeholder-color: @muted; }
listview { columns: 2; lines: 6; spacing: 7px; }
element { padding: 10px; border-radius: 10px; }
element selected { background-color: @bg-alt; border: 1px; border-color: @accent; }
element-icon { size: 28px; margin: 0 10px 0 0; }
element-text { vertical-align: 0.5; }
EOF

write_atomic "$swaync_dir/wallpaper-colors.css" <<EOF
/* Generated by DeblestiaSystemThemeSync.sh. */
@define-color noti-bg $background;
@define-color noti-bg-alt $background_alt;
@define-color noti-border-color $accent;
@define-color text-color $text;
@define-color noti-muted $muted;
EOF
if [ -f "$swaync_dir/style.css" ]; then
    temporary="$(mktemp "$swaync_dir/.style.XXXXXX")"
    {
        printf '@import "wallpaper-colors.css";\n'
        sed '/@import.*wallust\/colors-waybar\.css/d;/@import "wallpaper-colors\.css";/d' \
            "$swaync_dir/style.css"
    } >"$temporary"
    mv "$temporary" "$swaync_dir/style.css"
fi

for command_name in kitty ghostty rofi swaync-client; do
    command -v "$command_name" >/dev/null 2>&1 && printf 'OK %s\n' "$command_name" || true
done
if command -v kitty >/dev/null 2>&1; then
    kitty @ set-colors --all "$kitty_theme" >/dev/null 2>&1 || true
    for pid in $(pidof kitty 2>/dev/null || true); do
        kill -SIGUSR1 "$pid" >/dev/null 2>&1 || true
    done
fi
command -v swaync-client >/dev/null 2>&1 && swaync-client -rs >/dev/null 2>&1 || true
command -v pkill >/dev/null 2>&1 && pkill -SIGUSR2 -x waybar >/dev/null 2>&1 || true