# Navigation Deblestia entre les bureaux.
# Trois doigts horizontalement sur le pavé tactile.
gesture = 3, horizontal, workspace

gestures {
    workspace_swipe_distance = 180
    workspace_swipe_cancel_ratio = 0.25
    workspace_swipe_min_speed_to_force = 15
    workspace_swipe_create_new = true
    workspace_swipe_forever = true
    workspace_swipe_direction_lock = true
}
